### ISSUE TITLE
Issues when reporting target stream

### ISSUE THREAD

**Issue by fzoric8** [osrf/mbzirc#228]
Hi, 

We've been running reduced simulation to record video of whole simulation. 

We've been following instructions found on wiki and we get following output in our `events.yaml`: 
```
event:
  id: 1
  type: stream_start_request
  time_sec: 31
  elapsed_real_time: 135
  elapsed_sim_time: 18
  total_score: 18
  data: success
- event:
  id: 2
  type: target_reported_in_stream
  time_sec: 264
  elapsed_real_time: 1629
  elapsed_sim_time: 251
  total_score: 251
  data: vessel::516::332
```
Stream has started and vessel is detected, however, after 3 detections as this one (correct pixel and correct vessel) we get `vessel_id_failure`. 

![Screenshot from 2022-09-06 18-22-33](https://user-images.githubusercontent.com/26651809/188689548-0eadb70a-334e-4bc8-8d96-3cca59cf9077.png)

I'm providing screenshot for convenience. 

If we compare image saved in logs and stuff logged in `events.yaml`, everything seems fine, what else could be a problem regarding `vessel_id_failure`? 

Thank you in advance.
